FROM public.ecr.aws/lambda/python:3.9

#copy requirements 
COPY requirements.txt .

#installing python dependencies
RUN pip install --no-cache-dir -r requirements.txt

#copy app and model code
COPY app/ ${LAMBDA_TASK_ROOT}/app/
COPY model/ ${LAMBDA_TASK_ROOT}/model/

#copy lambda handler
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}/

#set the lambda handler
CMD ["lambda_handler.handler"]