
FROM public.ecr.aws/lambda/python:3.9


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY main.py ${LAMBDA_TASK_ROOT}/
COPY schemas.py ${LAMBDA_TASK_ROOT}/
COPY lambdahandler.py ${LAMBDA_TASK_ROOT}/
COPY model/ ${LAMBDA_TASK_ROOT}/model/


CMD ["lambdahandler.handler"]